deploy:
      stage: deploy
      script:
        - apt-get update -qq && apt-get install -y -qq lftp
        - lftp sftp://$USERNAME:'$PASSWORD'@$HOST -e 'ls; exit;'
        - echo "deployment complete"
      only:
        - master