deploy:
      stage: deploy
      script:
        - apt-get update -qq && apt-get install -y -qq lftp
        - lftp sftp://$USERNAME:'$PASSWORD'@$HOST -e 'set sftp:auto-confirm yes;set ssl:verify-certificate no;mirror -Rv ./ /home/www/apps/psyphy  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/; exit;'
        - echo "deployment complete"
      only:
        - master